//package SpringBoot.mapper;
//
//import SpringBoot.dto.EmployeeDTO;
//import SpringBoot.dto.EmployeePatchDTO;
//import SpringBoot.entity.Employee;
//
//@Component
//public class EmployeeMapper {
//    // Method for PUT Mapping (Updating all the fields)
//    public void updateEntity(Employee existing, EmployeeDTO employeeDTO){
//        existing.setName(employeeDTO.getName());
//        //Continue with other parameters
//        ...
//        ...
//        ...
//        ...
//        ...
//
//    }
//
//    //Method for Patch Mapping (Updating only user provided fields (Partially))
//    public void mergeNotNull(Employee existing, EmployeePatchDTO patchDTO){
//        if(patchDTO.getName() != null) existing.setName(patchDTO.getName());
//        //Continue with other parameters
//        ...
//        ...
//        ...
//        ...
//        ...
//    }
//
//    public EmplyeeDTO toDTO(Employee employee){
//        return new EmployeeDTO(
//                employee.getId();
//                employee.getName();
//                employee.getEmail();
//                //Continue with other fields
//        ...
//        ...
//        ...
//        ...
//        ...
//        )
//    }
//}
